/**
 * Type declarations for the cloudflare:test module.
 * This tells TypeScript what bindings are available in the test environment.
 * 
 * The Env interface is generated by `wrangler types` in worker-configuration.d.ts
 */

import "cloudflare:test";
import type { D1Migration } from "cloudflare:test";

declare module "cloudflare:test" {
    interface ProvidedEnv {
        TLDL_DATA: KVNamespace;
        MAX_EPISODE_MINUTES: string;
        CACHE_TTL_DAYS: string;
        DEFAULT_TEMPLATE: string;
        TLDL_QUEUE: Queue;
        DB: D1Database;
    }
}

declare module "vitest" {
    interface ProvidedContext {
        DB_MIGRATIONS: D1Migration[];
    }
}
