/**
 * PDF Generation Service
 * Generates downloadable PDFs containing episode summary and transcript
 */

import { jsPDF } from "jspdf";

export interface PdfContent {
    podcastName: string;
    episodeTitle: string;
    episodeDate: string;
    episodeDuration: number;
    summary: string;
    summaryTemplate: string;
    transcript: string;
    expiresAt: string;
}

/**
 * Strip markdown formatting to plain text
 */
function stripMarkdown(md: string): string {
    if (!md) return "";

    let text = md;

    // Remove headers
    text = text.replace(/^#{1,6}\s+/gm, "");

    // Remove bold/italic
    text = text.replace(/\*\*\*(.+?)\*\*\*/g, "$1");
    text = text.replace(/\*\*(.+?)\*\*/g, "$1");
    text = text.replace(/\*(.+?)\*/g, "$1");
    text = text.replace(/___(.+?)___/g, "$1");
    text = text.replace(/__(.+?)__/g, "$1");
    text = text.replace(/_(.+?)_/g, "$1");

    // Remove code blocks
    text = text.replace(/```[\s\S]*?```/g, (match) => {
        return match.slice(3, -3).trim();
    });

    // Remove inline code
    text = text.replace(/`(.+?)`/g, "$1");

    // Remove blockquotes
    text = text.replace(/^>\s+/gm, "");

    // Remove links but keep text
    text = text.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");

    // Remove images
    text = text.replace(/!\[([^\]]*)\]\([^)]+\)/g, "");

    // Clean up list markers
    text = text.replace(/^[-*+]\s+/gm, "• ");
    text = text.replace(/^\d+\.\s+/gm, "");

    // Clean up extra whitespace
    text = text.replace(/\n{3,}/g, "\n\n");

    return text.trim();
}

/**
 * Format duration in seconds to human readable string
 */
function formatDuration(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);

    if (hours > 0) {
        return `${hours}h ${minutes}m`;
    }
    return `${minutes} min`;
}

/**
 * Format ISO date string to readable format
 */
function formatDate(dateString: string): string {
    const date = new Date(dateString);
    return new Intl.DateTimeFormat("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
    }).format(date);
}

/**
 * Generate a PDF document for an episode
 */
export function generateEpisodePdf(content: PdfContent): ArrayBuffer {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let yPosition = margin;

    // Helper to add footer to each page
    const addFooter = () => {
        const footerY = pageHeight - 10;
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text("Generated by TLDL", margin, footerY);
        doc.text(
            `Expires: ${formatDate(content.expiresAt)}`,
            pageWidth - margin,
            footerY,
            { align: "right" }
        );
        doc.text(
            `Page ${doc.getNumberOfPages()}`,
            pageWidth / 2,
            footerY,
            { align: "center" }
        );
    };

    // Helper to check if we need a new page
    const checkNewPage = (neededHeight: number) => {
        if (yPosition + neededHeight > pageHeight - 20) {
            addFooter();
            doc.addPage();
            yPosition = margin;
            return true;
        }
        return false;
    };

    // Helper to add wrapped text and return new Y position
    const addWrappedText = (
        text: string,
        fontSize: number,
        lineHeight: number = 1.4
    ): void => {
        doc.setFontSize(fontSize);
        const lines = doc.splitTextToSize(text, contentWidth);
        const lineHeightMm = (fontSize * lineHeight * 0.352778); // Convert pt to mm

        for (const line of lines) {
            checkNewPage(lineHeightMm);
            doc.text(line, margin, yPosition);
            yPosition += lineHeightMm;
        }
    };

    // =========================================================================
    // Header Section
    // =========================================================================

    // TLDL branding
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("TLDL - Too Long Didn't Listen", margin, yPosition);
    yPosition += 8;

    // Podcast name
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    const podcastLines = doc.splitTextToSize(content.podcastName, contentWidth);
    doc.text(podcastLines, margin, yPosition);
    yPosition += podcastLines.length * 5 + 2;

    // Episode title
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(content.episodeTitle, contentWidth);
    doc.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * 7 + 2;

    // Episode metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    const metaText = `${formatDate(content.episodeDate)} • ${formatDuration(content.episodeDuration)}`;
    doc.text(metaText, margin, yPosition);
    yPosition += 10;

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // =========================================================================
    // Summary Section
    // =========================================================================

    // Section header
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", margin, yPosition);
    yPosition += 3;

    // Template badge
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "italic");
    doc.text(`Template: ${content.summaryTemplate}`, margin, yPosition);
    yPosition += 8;

    // Summary content
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const summaryText = stripMarkdown(content.summary);
    if (summaryText) {
        addWrappedText(summaryText, 11);
    } else {
        doc.setFontSize(11);
        doc.setTextColor(128, 128, 128);
        doc.text("No summary available.", margin, yPosition);
        yPosition += 6;
    }

    yPosition += 10;

    // Divider line
    checkNewPage(15);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // =========================================================================
    // Transcript Section
    // =========================================================================

    // Section header
    checkNewPage(20);
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Full Transcript", margin, yPosition);
    yPosition += 8;

    // Transcript content
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    if (content.transcript) {
        addWrappedText(content.transcript, 10, 1.5);
    } else {
        doc.setFontSize(10);
        doc.setTextColor(128, 128, 128);
        doc.text("No transcript available.", margin, yPosition);
        yPosition += 5;
    }

    // Add footer to the last page
    addFooter();

    // Return as ArrayBuffer
    return doc.output("arraybuffer");
}
